'
' Automatically generated by AjGenesis for Node.js
' https://github.com/ajlopez/AjGenesisNode
' Company ajlopez.com
'

Module Module1

    Sub Main()
        System.Console.WriteLine("Hello, World")
    End Sub

End Module
