'
' Automatically generated by AjGenesis for Node.js
' https://github.com/ajlopez/AjGenesisNode
' Company ${project.company}
'

Module Module1

    Sub Main()
        System.Console.WriteLine("${project.message}")
    End Sub

End Module
