//
// Automatically generated by AjGenesis
// Node.js Project https://github.com/ajlopez/AjGenesisNode
// Original Project http://www.ajlopez.com/ajgenesis
//

using System;
using System.Collections.Generic;
using System.Text;

namespace ${project.name}Cs
{
    class Program
    {
        static void Main(string[] args)
        {
			Console.WriteLine("${project.message}");
        }
    }
}

