'
' Automatically generated by AjGenesis
' Node.js Project https://github.com/ajlopez/AjGenesisNode
' Original Project http://www.ajlopez.com/ajgenesis
'

Module Module1

    Sub Main()
        Console.WriteLine("${project.message}")
    End Sub

End Module
